"""ProjectOrder and related models

Revision ID: 0ae6ea9f17f3
Revises: 589f01169cec
Create Date: 2024-03-31 01:52:55.570971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ae6ea9f17f3"
down_revision: Union[str, None] = "589f01169cec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("company_website", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_company"), "customer", ["company"], unique=False
    )
    op.create_index(
        op.f("ix_customer_email"), "customer", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_customer_full_name"), "customer", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_customer_ip_address"),
        "customer",
        ["ip_address"],
        unique=False,
    )
    op.create_table(
        "project_order_budget",
        sa.Column("value_from", sa.Integer(), nullable=False),
        sa.Column("value_to", sa.Integer(), nullable=True),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_order_budget_active"),
        "project_order_budget",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_budget_value_from"),
        "project_order_budget",
        ["value_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_budget_value_to"),
        "project_order_budget",
        ["value_to"],
        unique=False,
    )
    op.create_table(
        "project_order_referral_source",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_order_referral_source_active"),
        "project_order_referral_source",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_referral_source_name"),
        "project_order_referral_source",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_project_order_referral_source_position"),
        "project_order_referral_source",
        ["position"],
        unique=False,
    )
    op.create_table(
        "project_order_service",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_order_service_active"),
        "project_order_service",
        ["active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_service_name"),
        "project_order_service",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_project_order_service_position"),
        "project_order_service",
        ["position"],
        unique=False,
    )
    op.create_table(
        "project_order",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("budget_id", sa.Integer(), nullable=True),
        sa.Column("referral_source_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("deadline_date", sa.Date(), nullable=True),
        sa.Column(
            "hard_deadline",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("details", sa.String(), nullable=True),
        sa.Column("technical_assignment", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["project_order_budget.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["referral_source_id"],
            ["project_order_referral_source.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_order_budget_id"),
        "project_order",
        ["budget_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_customer_id"),
        "project_order",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_deadline_date"),
        "project_order",
        ["deadline_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_hard_deadline"),
        "project_order",
        ["hard_deadline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_referral_source_id"),
        "project_order",
        ["referral_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_order_start_date"),
        "project_order",
        ["start_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_order_start_date"), table_name="project_order"
    )
    op.drop_index(
        op.f("ix_project_order_referral_source_id"), table_name="project_order"
    )
    op.drop_index(
        op.f("ix_project_order_hard_deadline"), table_name="project_order"
    )
    op.drop_index(
        op.f("ix_project_order_deadline_date"), table_name="project_order"
    )
    op.drop_index(
        op.f("ix_project_order_customer_id"), table_name="project_order"
    )
    op.drop_index(
        op.f("ix_project_order_budget_id"), table_name="project_order"
    )
    op.drop_table("project_order")
    op.drop_index(
        op.f("ix_project_order_service_position"),
        table_name="project_order_service",
    )
    op.drop_index(
        op.f("ix_project_order_service_name"),
        table_name="project_order_service",
    )
    op.drop_index(
        op.f("ix_project_order_service_active"),
        table_name="project_order_service",
    )
    op.drop_table("project_order_service")
    op.drop_index(
        op.f("ix_project_order_referral_source_position"),
        table_name="project_order_referral_source",
    )
    op.drop_index(
        op.f("ix_project_order_referral_source_name"),
        table_name="project_order_referral_source",
    )
    op.drop_index(
        op.f("ix_project_order_referral_source_active"),
        table_name="project_order_referral_source",
    )
    op.drop_table("project_order_referral_source")
    op.drop_index(
        op.f("ix_project_order_budget_value_to"),
        table_name="project_order_budget",
    )
    op.drop_index(
        op.f("ix_project_order_budget_value_from"),
        table_name="project_order_budget",
    )
    op.drop_index(
        op.f("ix_project_order_budget_active"),
        table_name="project_order_budget",
    )
    op.drop_table("project_order_budget")
    op.drop_index(op.f("ix_customer_ip_address"), table_name="customer")
    op.drop_index(op.f("ix_customer_full_name"), table_name="customer")
    op.drop_index(op.f("ix_customer_email"), table_name="customer")
    op.drop_index(op.f("ix_customer_company"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
