"""M2M relationship between ProjectOrder and ProjectOrderService

Revision ID: 173f75ea2247
Revises: 0ae6ea9f17f3
Create Date: 2024-04-05 23:04:34.276865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "173f75ea2247"
down_revision: Union[str, None] = "0ae6ea9f17f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_order_service_association",
        sa.Column("project_order_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_order_id"],
            ["project_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["project_order_service.id"],
        ),
        sa.PrimaryKeyConstraint("project_order_id", "service_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_order_service_association")
    # ### end Alembic commands ###
