"""project_tags_association_table_ondelete

Revision ID: 3fd234363d5a
Revises: 01b0dba759e4
Create Date: 2023-11-17 00:18:28.151358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd234363d5a'
down_revision: Union[str, None] = '01b0dba759e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_tags_association_table_project_id_fkey', 'project_tags_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'project_tags_association_table', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_tags_association_table', type_='foreignkey')
    op.create_foreign_key('project_tags_association_table_project_id_fkey', 'project_tags_association_table', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
