"""ProjectBudget - fields changes

Revision ID: b9cbac8cf84e
Revises: ff996a790145
Create Date: 2023-11-23 01:20:11.303801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cbac8cf84e'
down_revision: Union[str, None] = 'ff996a790145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_budget', 'start_amount',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('project_budget', 'secondary_amount',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('project_budget', 'budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_budget', sa.Column('budget', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('project_budget', 'secondary_amount',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('project_budget', 'start_amount',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
