"""project_preview_image

Revision ID: 6b4f06e14a2a
Revises: bc593d3ba969
Create Date: 2023-11-09 18:11:15.224654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6b4f06e14a2a'
down_revision: Union[str, None] = 'bc593d3ba969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('preview_image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'preview_image')
    # ### end Alembic commands ###
