"""ProjectBudget - secondary_amount field changed to nullable=True

Revision ID: ff996a790145
Revises: fcf3bd8748e6
Create Date: 2023-11-22 23:26:27.327419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ff996a790145'
down_revision: Union[str, None] = 'fcf3bd8748e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_budget', 'secondary_amount',
                    existing_type=sa.SMALLINT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_budget', 'secondary_amount',
                    existing_type=sa.SMALLINT(),
                    nullable=False)
    # ### end Alembic commands ###
