"""project_tags_association

Revision ID: 1e28716a240f
Revises: 01b0dba759e4
Create Date: 2023-11-18 13:37:12.745706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1e28716a240f'
down_revision: Union[str, None] = '01b0dba759e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tags_association',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('project_tag_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['project_tag_id'], ['project_tags.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('project_id', 'project_tag_id', name='idx_unique_project_tag')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tags_association')
    # ### end Alembic commands ###
