"""project_filter_type

Revision ID: 01b0dba759e4
Revises: 6b4f06e14a2a
Create Date: 2023-11-11 20:49:56.020138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0dba759e4'
down_revision: Union[str, None] = '6b4f06e14a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_filter_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('projects', sa.Column('filter_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'project_filter_types', ['filter_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'filter_type_id')
    op.drop_table('project_filter_types')
    # ### end Alembic commands ###
