"""project_and_project_tags

Revision ID: bc593d3ba969
Revises: 9d5f32c3e909
Create Date: 2023-11-08 23:01:20.861532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bc593d3ba969'
down_revision: Union[str, None] = '9d5f32c3e909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tags',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=45), nullable=False),
                    sa.Column('img', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('source_link', sa.String(), nullable=True),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('project_tags_association_table',
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.Column('project_tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
                    sa.ForeignKeyConstraint(['project_tag_id'], ['project_tags.id'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tags_association_table')
    op.drop_table('projects')
    op.drop_table('project_tags')
    # ### end Alembic commands ###
