"""Customer company nullable True

Revision ID: 323a3a244275
Revises: 173f75ea2247
Create Date: 2024-04-28 12:33:46.206313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "323a3a244275"
down_revision: Union[str, None] = "173f75ea2247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer", "company", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customer", "company", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
