"""BotUser model

Revision ID: bf8fdb1b03db
Revises: 323a3a244275
Create Date: 2024-11-02 10:15:06.820449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf8fdb1b03db"
down_revision: Union[str, None] = "323a3a244275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_user",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("RU", "UA", "EN", name="bot_user_language"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bot_user_user_id"), "bot_user", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bot_user_user_id"), table_name="bot_user")
    op.drop_table("bot_user")
    # ### end Alembic commands ###
