version: "3.8"

services:
  postgresql:
    image: "postgres:15"
    restart: always
    container_name: "postgresql"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: "app"
    depends_on:
      - postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - .env.dev
    ports:
      - "8000:${API_APP_PORT}"
    volumes:
      - .:/app/api
      - static_data:/app/api/${STATIC_DIR}

volumes:
  postgres_data:
  static_data: